# Request
int32 id
robot_interfaces/ImgDetectionData selected_obj

---
# Response
bool movement_success # did the wheels stall
bool proximity_success # are we close enough to the object to move to grasping state
string movement_message # message from arduino about movement status
