# Goal: the max number to count to and the wait duration
int32 id
robot_interfaces/ImgDetectionData selected_obj
---
# Result: the final current number reached
int32 current_number
---
# Feedback: the progress made as a percentage
string current_stage                    # e.g. "approaching", "grasping", "lifting"
float32 progress                      
bool success
